# Generated by Django 3.2.7 on 2021-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaRua', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('numeroDaResidencia', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('pontoDeReferencia', models.CharField(max_length=250)),
                ('complemento', models.CharField(max_length=250)),
            ],
        ),
    ]
