# Generated by Django 3.2.7 on 2021-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], verbose_name='Turno')),
                ('inicioFuncionamento', models.TimeField()),
                ('finalFuncionamento', models.TimeField()),
            ],
        ),
    ]
