# Generated by Django 3.2.7 on 2021-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polo', '0001_initial'),
        ('horario_funcionamento', '0001_initial'),
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoSetor', models.CharField(max_length=250, verbose_name='Nome do Setor')),
                ('ramal', models.CharField(max_length=250, verbose_name='Ramal')),
                ('numeroWhatsapp', models.CharField(blank=True, max_length=21, null=True, verbose_name='Nome')),
                ('bloco', models.CharField(max_length=250, verbose_name='Bloco')),
                ('colaborador', models.ManyToManyField(to='colaborador.Colaborador', verbose_name='Colaborador')),
                ('horarioFuncionamento', models.ManyToManyField(to='horario_funcionamento.HorarioFuncionamento', verbose_name='Horario de Funcionamento')),
                ('polo', models.ManyToManyField(to='polo.Polo', verbose_name='Polo')),
            ],
        ),
    ]
