# Generated by Django 3.2.7 on 2021-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('polo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='endereco',
        ),
        migrations.AddField(
            model_name='polo',
            name='endereco',
            field=models.ManyToManyField(to='endereco.Endereco', verbose_name='Endereço'),
        ),
    ]
